Docs 1497 tc on scale
freenas/documentation pull request #464
Opened 2021-01-06 17:30 UTC by q5sys

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2021-01-07 17:11 UTC, BonnieF requested changes
There needs to be a break above each graphic.
A period needs to be after the following sentences:
Click Choose.
Set the image Tag to Latest. (change image Tag to **Image Tag**)
To confirm these setting click Submit.
Image Repository needs to be **Image Repository**
Container Settings needs to be changed to **Container Settings**
Network Settings needs to be changed to **Network Settings**
Container Port and Node Port each need to be **Container Port** and **Node Port**
Host Path needs to be **Host Path**
Volumes needs to be **Volumes**

2021-01-07 18:40 UTC, q5sys commented
I'm clarifying with Tim the way he wants the different font used.  If memory serves when we started with the new site the decision was made that bold is used for things that are clickable or higher level things Like 'system > general'.  No formatting or Code formatting was for things people would type or were CLI messages, and italics was for field names.
But that might have changed since Feb/March 2020.  I've asked him to make a determination so we're all on the same page.
I dont care what we do, but we should all be consistent. I'm leaving this ticket open until we get a decision from him.  I'll update this based on his decision.

2021-01-15 14:49 UTC, Mrt134 approved these changes

2021-01-15 14:57 UTC, merged

2021-01-15 14:59 UTC, Mrt134 commented
I reviewed the article and tweaked it a little in spots and expanded it in others. Bold syntax for buttons and italics for section titles and other things works for now. Current plan is to plan out a syntax review of content on the site whenever I can get the style guide written up, but those two elements are currently unlikely to change.