Docs 1066
freenas/documentation pull request #470
Opened 2021-01-07 18:47 UTC by q5sys

Thanks for contributing to TrueNAS documentation! By opening a Pull Request, you're acknowledging that your changes will be distributed under the [Creative Commons 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

2021-01-07 19:00 UTC, iXTimExample commented on content/en/hub/scale/_index.md
> +TrueNAS SCALE is a free and Open Source Hyperconverged Infrastructure (HCI) solution. Built on TrueNAS CORE, SCALE adds Linux Containers, KVM, and scale-out ZFS storage capabilities.
Lets linkify "TrueNAS SCALE" to the updated overview page

2021-01-07 19:09 UTC, BonnieF requested changes
Just need a period after:
Articles about the in-development TrueNAS SCALE project

2021-01-07 19:12 UTC, q5sys commented
> Just need a period after:
> Articles about the in-development TrueNAS SCALE project

@Mrt134  Are we putting periods in titles and descriptions now?  I missed memo that if we are.

2021-01-07 19:18 UTC, iXTimExample commented
When we're writing a full sentence in the description, we should end with a period.

2021-01-07 19:20 UTC, q5sys commented
ready for re-review

2021-01-08 16:30 UTC, Mrt134 approved these changes

2021-01-08 16:31 UTC, merged